name: money_tracker
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  provider: ^6.1.5
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0
  build_runner: ^2.4.13
flutter:
  uses-material-design: true
  assets:
    - assets/data/
